### ISSUE TITLE
Blocker-Unable to run dividcompute

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/dividenda#2]
QA2 env. Bloks.io
Iteration 10. When running dividcompute using ellaevery wallet in bloks.io, encountered Error: inline action's authorizing actor dividenda does not exist. 

![image](https://user-images.githubusercontent.com/77765830/117226286-6b012100-ae68-11eb-809e-7eba7768f8bb.png)

**Comment by andyzal** [comment]
This was corrected in version 135 time ago.

**Comment by judytan21** [comment]
Yeah. Was about to do it but you beat me to it. Thanks.
