### ISSUE TITLE
Incorrect allocation of OPTIONs to freeosdaodao

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/dividenda#3]
QA2 env.
DIvidcompute ran successfully. However, the allocation of OPTIONs to freeosdaodao was incorrect for iteration 9, 13 and 14.
Below shows the NFTs before running dividcompute. It also shows the deposits, actual/expected allocations to freeosdaodao afrer running dividcompute.
It appears that dividcompute has included the NFTs that were already paid off in the deduction before allocating to freeosdaodao.
Name.        Cap      Percentage                         Mint_date.                     Lock    Threshold.               rates_left.      Accrued
ellaevery        1       2.00000000000000000      2021-04-30T00:48:15       0      100.0000 OPTION        2               0.0000 OPTION
verovera         2      3.00000000000000000      2021-05-05T02:55:22       0      200.0000 OPTION        2               0.0000 OPTION
deliadally       3      1.00000000000000000      2021-05-05T03:39:07        0      300.0000 OPTION        2               0.0000 OPTION

Iteration | Deposit | ellaevery | verovera | deliadally | freeosdaodao(actual) | Tot for NFTs | freeosdaodao(expected)
9 | 8250 | 165 | 200 | 82.5 | 7755 | 447.5 | 8250-447.5=7802.5
13 | 6800 | 136 | nil | 68 | 6392 | 204 | 6800-204=6596
14 | 3400 | nil | nil | 34 | 3264 | 34 | 3400-34=3366
![image](https://user-images.githubusercontent.com/77765830/118060833-cd699c80-b3e7-11eb-9a75-d3a8e2c15809.png)
![image](https://user-images.githubusercontent.com/77765830/118060854-dc504f00-b3e7-11eb-83de-b6b3f455e99a.png)
![image](https://user-images.githubusercontent.com/77765830/118060873-e83c1100-b3e7-11eb-9b2d-5a5540b62a88.png)

**Comment by andyzal** [comment]
The way how the remaining founds are counted for dao account are not longer counted as a remaining percentage from pool but subtracted for currently processed iteration deposit firstly for paid NFTs (taking thresholds into accounts) and then remaining are transferred to DAO. This should solve the issue. Alsdo the log collection table was added to better observe deposit processing.. Note: this is only deployed on dev. On qa2 will be deployed this Friday.

**Comment by judytan21** [comment]
17/05/21 Retested. Fixed. Close issue.
