### ISSUE TITLE
POINT symbol appearing twice in transaction memo.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/dividenda#9]
28/2/22 Post Launch Dividend Testing -> v1.43 Env: QA5, Contracts: freeos5, freeoscfg5, freeosdiv5
On checking the freeosdiv5 transactions in bloks.io after dividcompute was run on 24/2/22 iteration 4, 
1. POINT symbol appearing twice in transaction memo -> memo: Your week 4 share of 5500.0000 POINT POINT. 

![Account - Proton Testnet 28-02-2022 10-47-56](https://user-images.githubusercontent.com/77765830/155901367-34da8ab9-430b-45d3-8ab9-98b25ba620a9.png)

**Comment by tommccann777** [comment]
I have corrected in release 1.44. Ready for retesting

**Comment by judytan21** [comment]
1 Mar 2022 Retest in release v1.44, transaction memo is now showing the POINT symbol once. Fixed.
![Account - Proton Testnet 01-03-2022 14-20-06](https://user-images.githubusercontent.com/77765830/156086581-a081dc7b-9e90-42fc-8c0d-1600789da20a.png)
